Traceback (most recent call last):
  File "dict_del.py", line 10, in ?
    del birthday['Faraday']
KeyError: 'Faraday'
