Traceback (most recent call last):
  File "key_error.py", line 5, in ?
    print birthday['Turing']
KeyError: 'Turing'
